export const STEP_IDS = {
  // Google steps
  CREATE_AUTOMATION_OU: 'G-1',
  CREATE_PROVISIONING_USER: 'G-2',
  GRANT_SUPER_ADMIN: 'G-3',
  VERIFY_DOMAIN: 'G-4',
  INITIATE_SAML_PROFILE: 'G-5',
  UPDATE_SAML_PROFILE: 'G-6',
  ASSIGN_SAML_PROFILE: 'G-7',
  EXCLUDE_AUTOMATION_OU: 'G-8',

  // Microsoft steps
  CREATE_PROVISIONING_APP: 'M-1',
  ENABLE_PROVISIONING_SP: 'M-2',
  AUTHORIZE_PROVISIONING: 'M-3',
  CONFIGURE_ATTRIBUTE_MAPPINGS: 'M-4',
  START_PROVISIONING: 'M-5',
  CREATE_SAML_APP: 'M-6',
  CONFIGURE_SAML_APP: 'M-7',
  RETRIEVE_IDP_METADATA: 'M-8',
  ASSIGN_USERS_SSO: 'M-9',
  TEST_SSO: 'M-10',
} as const;

export type StepId = typeof STEP_IDS[keyof typeof STEP_IDS];
